services:
  mem0_store:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      # 更明确的卷映射，指定主机上的具体路径
      - ./data/qdrant:/qdrant/storage
    environment:
      - QDRANT_ALLOW_RECOVERY=true # 允许从存储中恢复
    restart: unless-stopped # 确保容器在意外停止后重启
  openmemory-mcp:
    image: mem0/openmemory-mcp
    build: api/
    environment:
      - USER
    env_file:
      - api/.env
    depends_on:
      - mem0_store
    ports:
      - "8765:8765"
    volumes:
      - ./api:/usr/src/openmemory
      # 添加历史数据库的持久化
      - ./data/history:/app/history
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8765 --reload --workers 4"
    restart: unless-stopped # 确保服务持续运行
  openmemory-ui:
    build:
      context: ui/
      dockerfile: Dockerfile
    image: mem0/openmemory-ui:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8765
      - NEXT_PUBLIC_USER_ID=Anson
      # - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      # - NEXT_PUBLIC_USER_ID=${USER}

volumes:
  mem0_storage:
